### ISSUE TITLE
Dúvida de utilização do client

### ISSUE THREAD

**Issue by jpratesmoreira** [BoletoSimples/boletosimples-csharp#1]
rodrigo,

consigo usar essa sua api no ambiente sandbox?

poderia me passar algum exemplo para criar um boleto?

obrigado

**Comment by rscouto** [comment]
@jpratesmoreira 

Estamos com uma versão inicial eu publiquei o pacote apenas com o intuito de testar toda configuração de deploy.

Atualmente só subi a API de carteiras de clientes, toda ajuda é bem vinda, as proximas da fila são a API de boletos e clientes, que possivelmente ainda essa semana subam porque eu também estou precisando nos projetos da empresa. Logo após vem as APIs de arquivo (remessa e retorno) e as outras em seguida.

Quando subir os boletos terão exemplos nos testes integrados para te auxiliar na utilização.

**Comment by rscouto** [comment]
Quanto a apontar o client para o ambiente sandbox no readme do projeto explico as configurações que precisam ter no seu arquivo de configuração (.config). Que o mesmo onde fica sua connection string por exemplo.

Obs: Não abra uma issue com o nome de teste, quase deletei sem ler, porque **teste** pra mim é **teste**...rsrs.
